### ISSUE TITLE
Roadmap 2.0.0

### ISSUE THREAD

**Issue by lesander** [lesander/fritzbox.js#1]
_See issue #5 for the Roadmap of v2.1.0_

## 2.0.0
- [x] Rewrite to `async/await` ES6 and update for `06.83`:
    - [x] `fritz.getSmartDevices()`
    - [x] `fritz.toggleSwitch()`
    - [x] `fritz.getCalls()`
    - [x] `fritz.getTamMessages()`
    - [x] `fritz.downloadTamMessage()`
    - [x] `fritz.markTamMessageAsRead()`
    - [x] `fritz.dialNumber()`
    - [x] `fritz.getActiveCalls()`
    - [x] `fritz.getPhonebook()`
    - [x] `fritz.getSessionId()`
    - [x] `fritz.getVersion()`
    - [x] `fritz.getVersionNumber()`
    - [x] `fritz.request()`
- [x] Add `fritz.markTamMessageAsRead()`
- [x] Add `fritz.dialNumber()`
- [x] Add `fritz.getPhonebook()`
- [x] Add `fritz.getVersion()`
- [x] Add callmonitor.
- [x] Update all unit tests.
- [x] Add some documentation.
- [x] Add GitHub pages landing page and docs.

**Comment by andig** [comment]
Hi Lesander,

I'm the author of https://github.com/andig/fritzapi. Could I interest you in joining forces and develop a library together?

Cheers,
Andi

**Comment by lesander** [comment]
Hi Andi (or Johann?),

That certainly seems like a good idea to me! How would you like to discuss this further?

Cheers,
Sander

**Comment by andig** [comment]
Hey Sander,

it’s Andi :) I’ve done fritzapi because I wanted to use my thermostats with homebridge and pimatic and especially the homebridge plugin has a bit of traction.

I’m more from the php world and my js isn’t the best, promises have been a fight. You have a cool website and apparently a much cleaner approach on js than me.

I’m wondering if we might find a path to have a next version of fritzapi and/or fritzbox.js that might be used by e.g. the depending homebridge plugin. If that would interest you we might do with a github organization together. I don’t care for the fritzapi name so much but using it with homebridge is something I’d like to keep.

So, not sure how best to proceed but if you want to explore the options feel free to email me at cpuidle@gmx.de <mailto:cpuidle@gmx.de>

Cheers,
Andi
