### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lesander** [lesander/fritzbox.js#5]
With `2.0.0` released, I will now focus on the following features for the next releases.
## 2.2.0
- [ ] Add rudimentary support for `7.0.1`.
    - [x] Make sure no functions break.
    - [ ] Check compatibility of old endpoints with new version.
- [ ] *WLAN and Home Network. (`wlan`)*
    - [ ] (Guest) get/set WLAN configuration.
        - [x] Add `fritz.getWlanKey()`
        - [ ] Add `fritz.setWlanKey()`
        - [x] Add `fritz.getWlanWPAType()`
        - [x] Add `fritz.isWlanEncrypted()`
        - [ ] Add `fritz.allowNewWlanDevices(boolean)`
        - [ ] Add `fritz.getQRCode()`
        - [ ] Add `fritz.enableWlan(guest=false)`
        - [ ] Add `fritz.disableWlan(guest=false)`
        - [ ] Start (Guest) WLAN WPS.
    - [ ] List active + inactive network connections (LAN+WLAN).
    - [ ] List connected USB devices.
    - [ ] Show WAN information.
- [ ] *Fritz!Box (`system`)*
    - [x] Add `fritz.updateAvailable()`
    - [x] Add `fritz.getBoxInfo()` (no auth required)
    - [x] Add `fritz.getSystemLog()`
    - [x] Add `fritz.getName()`
    - [ ] Add `fritz.setName()`
## 2.3.0
- [ ] *Telephony (`fon`)*
    - [ ] Add `fritz.listDectPhones()`
    - [ ] Add `fritz.uploadPhonebook()`
    - [ ] Add `fritz.getContact()`
    - [ ] Add `fritz.addContact()`
    - [ ] Add  `fritz.editContact()`
    - [ ] Add `fritz.removeContact()`
- [ ] *Fritz!NAS (`nas`)*
    - [ ] Add Fritz NAS and Media Server functions (list contents, CRUD files).
- [ ] *DECT Devices (`dect`)*
    - [ ] Improve `fritz.getSmartDevices()`.
        - [ ] View smart devices by group.
        - [ ] Standardize & translate keys from object.
## 3.0.0
- [ ] Add browser compatibility using Browserify and Babel or webpack (Whatever the cool kids use these days).
- [ ] Implement 2FA for 'Action Confirmation'
---

Any suggestions, pull requests or feedback is appreciated!

Still working through the change log of the new Fritz!OS `06.83`: http://web.archive.org/web/20171122064809/http://ftp.avm.de/fritz.box/fritzbox.fon_wlan_7390/firmware/english/info.txt

And now working through the change log of Fritz!OS `07.01`:
http://ftp.avm.de/fritzbox/fritzbox-4040/other/fritz.os/info_en.txt

**Comment by simonmilz** [comment]
Is this repo still maintained?

**Comment by lesander** [comment]
Periodically yes, @simonmilz 😅.
